### ISSUE TITLE
Show location in item description

### ISSUE THREAD

**Issue by dannycjones** [azai91/alfred-drive-workflow#28] opened 2017-05-28 16:33 UTC
I think it would be a handy feature to display the location of the file below the file name, since ambiguous file names can mean absolutely nothing in search results.

<img width="607" alt="screen shot 2017-05-28 at 17 27 36" src="https://cloud.githubusercontent.com/assets/4976211/26530330/f75cc2f6-43ca-11e7-925c-afe42f2fab11.png">

You can see descriptions in the screenshot below.

<img width="607" alt="screen shot 2017-05-28 at 17 29 05" src="https://cloud.githubusercontent.com/assets/4976211/26530347/3496cba8-43cb-11e7-898e-80288c040008.png">

**Comment by sorbits** [comment] 2017-07-11 10:08
This is a duplicate of #17

**Closed as completed** 2017-08-28 03:53 UTC
